### ISSUE TITLE
not work button

### ISSUE THREAD

**Issue by hukendo** [johngraciliano/simplewhite#14] opened 2015-11-13 06:10 UTC
button is not pressed
el capitano ff 42
![2015-11-13 12 30 08](https://cloud.githubusercontent.com/assets/15173839/11139870/1021e728-8a07-11e5-89f1-9ccbe5c5b1fb.png)

**Comment by johngraciliano** [comment] 2015-11-13 07:39
The issue is not present in my environment, _Windows 8_. It is likely to be a _mac_ specific issue.  Currently, I have no access to the _mac_ environment.  I need assistance solving this or any other issue specific to the _mac_ implementation.  So I may require you to test any potential solution.  I may also need other help figuring out the problem.  At this moment I will only investigate the issue.

**Comment by johngraciliano** [comment] 2015-11-18 05:35
I am currently changing the code for that panel, yet there is nothing in it that is specific to the operating system (OS).  I cannot see how could this be happening for that particular implementation and no other.  @hukendo: Please verify if this problem does not affect any other buttons.  If so, then I could get more clues about what to check in the code.  Otherwise I will need your help to diagnose the problem by sending me some code and perhaps inspecting Firefox as is implemented in your computer for me.

**Comment by hukendo** [comment] 2015-11-18 16:01
This problem does not affect other buttons. I think the problem solved itself. In the version of 44 this is no problem.

**Comment by johngraciliano** [comment] 2015-12-13 19:42
I just noticed the presence of the problem using **Firefox 42** on https://kissanime.to/.  I also confirmed the problem is not present with **Firefox 44** on the same website.  However the problem should not be there at all on any version.  I never noticed this problem before and it still I do not find it with other websites other websites I visit, e.g., http://www.majorgeeks.com/.  Indeed I find no problem when I visit http://nnm-club.me/ that you (@hukendo) posted (perhaps you would not find it on kissanime).  I have to see what can I do to fix it, but I have little clues as what may cause it, especially because of the erratic behavior.  At least now I have witnessed it, and it seems to behave consistently in one website.  I do not want it to simply go away before I can find the cause.

**Comment by johngraciliano** [comment] 2015-12-13 20:21
The access keys for the button still work, so the button is not disabled.  That is, even when the button cannot be pressed, the key combination [Alt]-D will disable the tracking protection for the site and the combination [Alt]-E will enable it.  These key combinations may differ non English locales.  This behaves as if the button was covered by a transparent object.

**Comment by johngraciliano** [comment] 2015-12-14 13:27
I believe the last commit fixes this issue.  I do not think this issue would be found in other versions of **Firefox** besides **42**, so it's a pity I did this work when there are only a few more days before **Firefox 43** is released.  Yet, there may be reasons to stick with **Firefox 42** (I did not like how the page scrolls in my system with the **43** candidate, but I find no such problem with **42**, **44** or **45**!).  I am not making a release just for this but I hope @hukendo or someone else repacks the theme and tries it under conditions they have found this problem to confirm it is now fixed.  I will close the issue within a day or two if no one can reproduce the problem because I now think is fixed.
Oh, I forgot to say:  Thank you @hukendo for the report, especially because I think it was a hard find, yet I think it could potentially affect any button close to the bottom of the identity panel.

---

Bugs do not go away, they go into cracks in the walls and hide unless you kill them.

**Closed as completed** 2015-12-31 17:00 UTC
