### ISSUE TITLE
A tab bug happens when Firefox stars on one tab

### ISSUE THREAD

**Issue by Devlinyang** [johngraciliano/simplewhite#29] opened 2016-05-12 07:34 UTC
@johngraciliano  ,hello!
A tab bug happens when Firefox stars on one tab,please see followed picture~
![baidushurufa_2016-5-12_15-30-16](https://cloud.githubusercontent.com/assets/19321703/15207168/e46d910c-1856-11e6-9b4f-6a813693a24e.png)

**Comment by Devlinyang** [comment] 2016-05-12 07:36
the version is 2.2b18.x1.17  on firefox 46.0.1

**Comment by johngraciliano** [comment] 2016-05-12 08:08
What OS?  I only have Windows 8 so I may need your assistance troubleshooting.  I see the tab (and the _open a new tab_ button)  show no border in your image.  Sometimes I see the borders do not who correctly after I switch to a _light theme_.  Does your problem go away if you hove on the tab?  Are you talking about something else?

**Comment by Devlinyang** [comment] 2016-05-12 08:31
My OS is Win7 64bit, yes ,as you said the tab have no borders initial，but when I hove/move or add a tab it return to normal. I really want assist you as I can~ I know little about code...
initial:
![1](https://cloud.githubusercontent.com/assets/19321703/15208666/52f9988e-185f-11e6-990f-a59a9e70af7d.png)
after add a tab:
![2](https://cloud.githubusercontent.com/assets/19321703/15208681/750401c6-185f-11e6-869e-2d6e88f4136b.png)

**Comment by johngraciliano** [comment] 2016-05-12 09:30
Thank you for your offer.  I may need your help but not yet.  I was actually able to confirm this issue in my system using Firefox 45 and Firefox 46.  However, it is not present with Firefox 44.0.2 nor Firefox 47 beta 4 (I have not tried other versions yet).  Since I am able to reproduce it locally, I will try to solve it without any more help for now.   Your help just pointing out the issue is much appreciated.  Please keep attention to the issue because I may still need help.

**Comment by johngraciliano** [comment] 2016-05-12 11:10
Good and bad news.  The good news is that I was able to find a solution that works in my system.  Recently, I have found problems while working on the implementation of the _Firebug_ theme for the _Developer Tools_, I made some quick analogies between those and this problem which lead me to a work around what I think causes this issue.  The bad news is that I want to complete more of the work regarding the _Developer Tools_ before I publish the next release.  Yet I may not complete that part before making a release with a solution to this issue because it is relevant since Firefox 45 (it may not be so important in Firefox 47!).  I may put the change that fixes this issue in this repository within a day before any release at AMO to have it closed.  Again, thank you @Devlinyang.

**Comment by johngraciliano** [comment] 2016-05-12 21:12
@Devlinyang:
Please verify the [latest release](https://github.com/johngraciliano/simplewhite/releases/tag/v2.2b18.x1.17%2B) fixes this issue.  Close the issue after you verify is fixed.  It may take a few more days before a release with the fix is published at AMO.

**Comment by Devlinyang** [comment] 2016-05-13 00:39
Thank U very much! I just online. I will check the result and close the issue~

**Comment by Devlinyang** [comment] 2016-05-13 00:49
@johngraciliano ,OK, it's done~very nice u~

**Closed as completed** 2016-05-13 00:50 UTC
